name: Clean Colab Notebook Metadata

on:
  push:
    paths:
      - "**/*.ipynb"

permissions:
  contents: write

jobs:
  clean-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install nbformat
        run: |
          pip install nbformat

      - name: Get list of modified .ipynb files
        id: notebooks
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1 || true
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.ipynb')
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Clean only changed notebooks
        run: |
          echo "${{ steps.notebooks.outputs.changed_files }}" > changed_files.txt
          xargs python .github/scripts/clean_colab_metadata.py < changed_files.txt

      - name: Commit and push changes if metadata was cleaned
        env:
          KEERTHI_PAT: ${{ secrets.KEERTHI_PAT }}
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "fix: clean Colab notebook metadata for GitHub rendering"
            git push https://x-access-token:${KEERTHI_PAT}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          else
            echo "No metadata changes detected."
          fi